Added support for loading file from bundle in directory
allaboutapps/Fetch pull request #33
Opened 2023-06-23 13:59 UTC by mpoimer

2023-06-26 06:43 UTC, wieweb commented on Package.swift
> +        .package(url: "https://github.com/Alamofire/Alamofire.git", from: "5.5.0"),
current version of alamofire is 5.7.0. we. could think about to update

2023-06-26 06:44 UTC, wieweb approved these changes

2023-06-26 07:31 UTC, mbuchetics requested changes

2023-06-29 09:53 UTC, mbuchetics approved these changes

2023-06-29 10:37 UTC, merged